# Copyright © 2025 Brent Tunnicliff <brent@tunnicliff.dev>

name: Pipeline

on:
  push:
  workflow_dispatch:

jobs:
  package:
    uses: Brent-Tunnicliff/workflow-common-apple/.github/workflows/common.yml@v1
    name: Package
    strategy:
      matrix:
        platform: ["iOS", "macOS", "tvOS", "watchOS", "visionOS"]
    with:
      platform: "${{ matrix.platform }}"
      scheme: "Package"
      skip_tests: false
